
# http server
http:
  # Addr specifies the TCP address for the server to listen on, in the form "host:port".
  addr: ":8080"

  # ReadTimeout is the maximum duration for reading the entire
  # request, including the body. A zero or negative value means
  # there will be no timeout.
  #
  # Because ReadTimeout does not let Handlers make per-request
  # decisions on each request body's acceptable deadline or
  # upload rate, most users will prefer to use
  # ReadHeaderTimeout. It is valid to use them both.
  read-timeout: 0s

  # ReadHeaderTimeout is the amount of time allowed to read
  # request headers. The connection's read deadline is reset
  # after reading the headers and the Handler can decide what
  # is considered too slow for the body. If ReadHeaderTimeout
  # is zero, the value of ReadTimeout is used. If both are
  # zero, there is no timeout.
  read-header-timeout: 0s

  # WriteTimeout is the maximum duration before timing out
  # writes of the response. It is reset whenever a new
  # request's header is read. Like ReadTimeout, it does not
  # let Handlers make decisions on a per-request basis.
  # A zero or negative value means there will be no timeout.
  write-timeout: 0s

  # IdleTimeout is the maximum amount of time to wait for the
  # next request when keep-alives are enabled. If IdleTimeout
  # is zero, the value of ReadTimeout is used. If both are
  # zero, there is no timeout.
  idle-timeout: 0s

  # MaxHeaderBytes controls the maximum number of bytes the
  # server will read parsing the request header's keys and
  # values, including the request line. It does not limit the
  # size of the request body.
  # If zero, DefaultMaxHeaderBytes is used.
  max-header-bytes: 0